#!/bin/bash
# Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Render the "Pinned components" table in README.md from the pins themselves,
# so the prose cannot drift away from what the build actually uses.  Values
# come from the environment when set (the Makefile exports them) and otherwise
# from the ARG defaults in docker/Dockerfile, the same resolution order
# patch-check.sh uses.
#
# The table is written between the marker comments in README.md; everything
# outside them is left untouched.
#
#   make readme         # rewrite the block in place
#   make readme-check   # fail if the block is stale (no write)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
DOCKERFILE="${DOCKERFILE:-${REPO_ROOT}/docker/Dockerfile}"
README="${README:-${REPO_ROOT}/README.md}"

BEGIN_MARK='<!-- BEGIN GENERATED PINS -->'
END_MARK='<!-- END GENERATED PINS -->'

MODE="write"
[[ "${1:-}" == "--check" ]] && MODE="check"

_arg() {
	if [[ -v "$1" ]]; then
		printf '%s\n' "${!1}"
	else
		grep -E "^ARG $1=" "${DOCKERFILE}" | head -1 | cut -d= -f2-
	fi
}

# github.com/o/r.git -> the browsable tree/commit URL for a ref, and a cell
# that shows a tag verbatim but abbreviates a 40-char SHA.
_ref_cell() {
	local url="$1" ref="$2" empty_note="$3" base
	if [[ -z "${ref}" ]]; then
		printf '%s' "${empty_note}"
		return
	fi
	base="${url%.git}"
	if [[ "${ref}" =~ ^[0-9a-f]{40}$ ]]; then
		printf '[`%s`](%s/commit/%s)' "${ref:0:7}" "${base}" "${ref}"
	else
		printf '[`%s`](%s/tree/%s)' "${ref}" "${base}" "${ref}"
	fi
}

_repo_cell() {
	local url="$1" base slug
	base="${url%.git}"
	slug="${base#https://github.com/}"
	printf '[`%s`](%s)' "${slug}" "${base}"
}

ROCM_VERSION="$(_arg ROCM_VERSION)"
NIXL_GIT_URL="$(_arg NIXL_GIT_URL)"; NIXL_REF="$(_arg NIXL_REF)"
MORI_GIT_URL="$(_arg MORI_GIT_URL)"; MORI_REF="$(_arg MORI_REF)"
UCX_GIT_URL="$(_arg UCX_GIT_URL)"; UCX_REF="$(_arg UCX_REF)"
HIPFILE_GIT_URL="$(_arg HIPFILE_GIT_URL)"; HIPFILE_REF="$(_arg HIPFILE_REF)"
FIO_GIT_URL="$(_arg FIO_GIT_URL)"; FIO_REF="$(_arg FIO_REF)"

_count_patches() {
	local dir="${REPO_ROOT}/patches/$1" n=0 p
	for p in "${dir}"/*.patch; do
		[[ -e "${p}" ]] && n=$((n + 1))
	done
	if [[ ${n} -eq 0 ]]; then
		printf 'pristine'
	elif [[ ${n} -eq 1 ]]; then
		printf '1 patch'
	else
		printf '%d patches' "${n}"
	fi
}

render() {
	printf '%s\n' "${BEGIN_MARK}"
	printf '<!-- Generated by docker/scripts/readme-pins.sh -- run `make readme` after bumping a pin. -->\n'
	printf '\n'
	printf '| Component | Pinned ref | Source | Local patches |\n'
	printf '|---|---|---|---|\n'
	printf '| ROCm base | `%s` | `rocm/dev-ubuntu-24.04:%s-full` | — |\n' \
		"${ROCM_VERSION}" "${ROCM_VERSION}"
	printf '| NIXL | %s | %s | %s |\n' \
		"$(_ref_cell "${NIXL_GIT_URL}" "${NIXL_REF}" '—')" \
		"$(_repo_cell "${NIXL_GIT_URL}")" "$(_count_patches nixl)"
	printf '| MORI | %s | %s | %s |\n' \
		"$(_ref_cell "${MORI_GIT_URL}" "${MORI_REF}" '—')" \
		"$(_repo_cell "${MORI_GIT_URL}")" "$(_count_patches mori)"
	printf '| UCX | %s | %s | %s |\n' \
		"$(_ref_cell "${UCX_GIT_URL}" "${UCX_REF}" '—')" \
		"$(_repo_cell "${UCX_GIT_URL}")" "$(_count_patches ucx)"
	printf '| hipFile | %s | %s | %s |\n' \
		"$(_ref_cell "${HIPFILE_GIT_URL}" "${HIPFILE_REF}" '_ROCm-packaged_')" \
		"$(_repo_cell "${HIPFILE_GIT_URL}")" "$(_count_patches hipfile)"
	printf '| fio | %s | %s | %s |\n' \
		"$(_ref_cell "${FIO_GIT_URL}" "${FIO_REF}" '_not built_')" \
		"$(_repo_cell "${FIO_GIT_URL}")" "$(_count_patches fio)"
	printf '\n'
	printf 'Resulting image tag:\n'
	printf '\n'
	printf '```\n%s\n```\n' \
		"${IMAGE_REF:-${IMAGE_NAME:-nixl-mori-test}:$("${SCRIPT_DIR}/image-tag.sh" "${DOCKERFILE}")}"
	printf '%s\n' "${END_MARK}"
}

grep -qF "${BEGIN_MARK}" "${README}" && grep -qF "${END_MARK}" "${README}" || {
	echo "readme-pins: ${README} is missing the ${BEGIN_MARK} / ${END_MARK} markers" >&2
	exit 1
}

block="$(render)"
new="$(awk -v begin="${BEGIN_MARK}" -v end="${END_MARK}" -v block="${block}" '
	$0 == begin { print block; skip = 1; next }
	$0 == end   { skip = 0; next }
	!skip       { print }
' "${README}")"

if [[ "${MODE}" == "check" ]]; then
	if diff -u "${README}" - <<<"${new}" >/dev/null; then
		echo "readme-pins: README.md pin table is up to date"
	else
		echo "readme-pins: README.md pin table is stale -- run 'make readme'" >&2
		diff -u "${README}" - <<<"${new}" >&2 || true
		exit 1
	fi
else
	printf '%s\n' "${new}" >"${README}"
	echo "readme-pins: wrote the pin table into ${README}"
fi
